package za.co.sjpret.virtualpet.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import za.co.sjpret.virtualpet.controller.Controller;
import za.co.sjpret.virtualpet.pet.Pet;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

//TODO Implement Animal Status
//TODO Picture of a kitten
//TODO Windows Notification is window is closed.

public class MainGui {
    private final Pet pet;
    private JFrame frame;
    private JPanel mainPanel;
    private JButton feed;
    private JButton exit;
    private JPanel menuBarPanel;
    private JLabel name;
    private JLabel age;
    private JLabel health;
    private JLabel food;

    public MainGui(Pet pet, Controller controller) {
        this.pet = pet;
        JMenuBar menuBar = new JMenuBar();
        JMenu about = new JMenu("About");
        JMenu manage = new JMenu("Manage");
        JMenu data = new JMenu("Data");
        JMenu view = new JMenu("View");
        JMenuItem viewOnDesktop = new JMenuItem("View On Desktop");
        JMenuItem saveData = new JMenuItem("Save Data");
        JMenuItem newPet = new JMenuItem("New Pet");
        JMenuItem deletePet = new JMenuItem("Kill Pet");
        JMenuItem credits = new JMenuItem("Credits");
        data.add(saveData);
        about.add(credits);
        manage.add(newPet);
        manage.add(deletePet);
        view.add(viewOnDesktop);
        menuBar.add(manage);
        menuBar.add(view);
        menuBar.add(data);
        menuBar.add(about);
        menuBarPanel.add(menuBar);
        name.setText("Name: " + pet.getName());
        frame = new JFrame();
        frame.setContentPane(mainPanel);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setSize(400, 400);
        frame.setResizable(false);
        frame.setTitle("Virtual Pet");
        frame.setLocationRelativeTo(null);
        update();
        frame.setVisible(true);
        credits.addActionListener(e -> JOptionPane.showMessageDialog(frame, "Created by SJ Pretorius", "Credits", JOptionPane.PLAIN_MESSAGE));
        feed.addActionListener(e -> pet.incrementFood((byte) 10));
        exit.addActionListener(e -> {
            controller.saveData();
            System.exit(0);
        });
        newPet.addActionListener(e -> controller.createNewPet());
        deletePet.addActionListener(e -> controller.removePet(pet));
        saveData.addActionListener(e -> controller.saveData());
    }

    public void update() {
        age.setText("Age: " + String.valueOf(pet.getAge()));
        health.setText("Health: " + String.valueOf(pet.getHealth()));
        food.setText("Food: " + String.valueOf(pet.getFood()));
    }

    public void showGui() {
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setEnabled(true);
        menuBarPanel = new JPanel();
        menuBarPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(menuBarPanel, BorderLayout.NORTH);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        mainPanel.add(panel1, BorderLayout.CENTER);
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 5, 5, 5), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, BorderLayout.NORTH);
        name = new JLabel();
        name.setText("Label");
        panel2.add(name, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        age = new JLabel();
        age.setText("Label");
        panel2.add(age, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        health = new JLabel();
        health.setText("Label");
        panel2.add(health, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        food = new JLabel();
        food.setText("Label");
        panel2.add(food, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel3, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        label1.setText("<Picture of Virtual Pet>");
        panel3.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        panel1.add(panel4, BorderLayout.SOUTH);
        feed = new JButton();
        feed.setText("Feed");
        panel4.add(feed, BorderLayout.WEST);
        exit = new JButton();
        exit.setText("Save and Exit");
        panel4.add(exit, BorderLayout.EAST);
        final JLabel label2 = new JLabel();
        label2.setHorizontalAlignment(0);
        label2.setText("Status: <Animal Status>");
        panel4.add(label2, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
